language: node_js

node_js:
  - "node"

jobs:
  include:
    - stage: test
      os: linux
      script: npm run test:ci

    - stage: build
      os: linux
      script:
        - npm run pack
        - npm run dist
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:
          - dist/switchql.snap
          - dist/switchql.AppImage
        skip_cleanup: true
        on:
          branch: master
          tags: true

    - stage: build
      os: osx
      script:
        - npm run pack
        - npm run dist
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file: dist/switchql.dmg
        skip_cleanup: true
        on:
          branch: master
          tags: true

    - stage: build
      filter_secrets: false
      os: windows
      script:
        - npm run pack
        - npm run dist
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file: dist\switchql.exe
        skip_cleanup: true
        on:
          branch: master
          tags: true
