export default [
    {
        tableName: 'author',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'author',
        columnName: 'name',
        isNullable: 'YES',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'book_order',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'book_order',
        columnName: 'book_id',
        isNullable: 'YES',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'FOREIGN KEY',
        foreignTableName: 'books',
        foreignColumnName: 'id',
    },
    {
        tableName: 'book_order',
        columnName: 'order_id',
        isNullable: 'YES',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'FOREIGN KEY',
        foreignTableName: 'order',
        foreignColumnName: 'id',
    },
    {
        tableName: 'books',
        columnName: 'genre_id',
        isNullable: 'YES',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'FOREIGN KEY',
        foreignTableName: 'genre',
        foreignColumnName: 'id',
    },
    {
        tableName: 'books',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'books',
        columnName: 'test',
        isNullable: 'YES',
        dataType: 'double precision',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'books',
        columnName: 'name',
        isNullable: 'YES',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'books',
        columnName: 'publish_date',
        isNullable: 'YES',
        dataType: 'date',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'books',
        columnName: 'author_id',
        isNullable: 'YES',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'FOREIGN KEY',
        foreignTableName: 'author',
        foreignColumnName: 'id',
    },
    {
        tableName: 'genre',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'genre',
        columnName: 'name',
        isNullable: 'YES',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'order',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'order',
        columnName: 'created_at',
        isNullable: 'YES',
        dataType: 'date',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'order',
        columnName: 'user_id',
        isNullable: 'YES',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'FOREIGN KEY',
        foreignTableName: 'user',
        foreignColumnName: 'id',
    },
    {
        tableName: 'order',
        columnName: 'status_id',
        isNullable: 'YES',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'FOREIGN KEY',
        foreignTableName: 'status',
        foreignColumnName: 'id',
    },
    {
        tableName: 'order',
        columnName: 'shipping_id',
        isNullable: 'YES',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'FOREIGN KEY',
        foreignTableName: 'shipping_method',
        foreignColumnName: 'id',
    },
    {
        tableName: 'shipping_method',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'shipping_method',
        columnName: 'method',
        isNullable: 'YES',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'status',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'status',
        columnName: 'code',
        isNullable: 'YES',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'user',
        columnName: 'id',
        isNullable: 'NO',
        dataType: 'integer',
        characterMaximumLength: null,
        constraintType: 'PRIMARY KEY',
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'user',
        columnName: 'phone_number',
        isNullable: 'YES',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'user',
        columnName: 'address',
        isNullable: 'YES',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
    {
        tableName: 'user',
        columnName: 'name',
        isNullable: 'NO',
        dataType: 'text',
        characterMaximumLength: null,
        constraintType: null,
        foreignTableName: null,
        foreignColumnName: null,
    },
];

